spring:
  cloud:
    gateway:
      server:
        webflux:

          routes:
            # POST → event-service
            - id: event-service-write
              uri: http://<EVENT-SERVICE-PUBLIC-URL>:8080
              predicates:
                - Path=/api/events,/api/events/**
                - Method=POST

            # GET → processing-service
            - id: processing-service-read
              uri: http://<PROCESSING-SERVICE-PUBLIC-URL>:8081
              predicates:
                - Path=/api/events,/api/events/**
                - Method=GET

            # Chaos, replay, webhook → processing-service
            - id: processing-service-ops
              uri: http://<PROCESSING-SERVICE-PUBLIC-URL>:8081
              predicates:
                - Path=/api/chaos/**,/api/replay/**,/api/webhook/**

          globalcors:
            add-to-simple-url-handler-mapping: true   # 🔥 IMPORTANT
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: false