server:
  port: 8081

spring:
  application:
    name: processing-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: resilience-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: mongodb://localhost:27017/resiliencelab
      database: resiliencelab

logging:
  pattern:
      console: "%d{HH:mm:ss} [%level] %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:


